//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_FunctiesUserControl 
    {
    
        /// <summary>
        /// udp_Functies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel udp_Functies;
    
    	/// <summary>
    	/// tmr_loader_Functies control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.Timer tmr_loader_Functies;
            
    	/// <summary>
    	/// pnl_Functies control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.WebControls.Panel pnl_Functies;
    
    	/// <summary>
    	/// udp_Functies_progress control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.UpdateProgress udp_Functies_progress;
    
        /// <summary>
        /// FunctieMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuTemplate FunctieMenu;
    
    	/// <summary>
        /// Functie_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Functie_Details;
    
        /// <summary>
        /// Functionarissen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Functionarissen;
    
        /// <summary>
        /// ClubCloud_Functie_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_Functie_DataSource;
    
        /// <summary>
        /// spgvpager_top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_top;
    
        /// <summary>
        /// ClubCloud_Functies_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridView Functies_Grid;
    
        /// <summary>
        /// spgvpager_bottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_bottom;
            
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}

