// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.0.0.285
//    <NameSpace>ClubCloud.Zimbra.Synchronization</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net45</CodeBaseTag><InitializeFields>All</InitializeFields><GenerateUnusedComplexTypes>False</GenerateUnusedComplexTypes><GenerateUnusedSimpleTypes>False</GenerateUnusedSimpleTypes><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableLazyLoading>False</EnableLazyLoading><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><AutomaticProperties>False</AutomaticProperties><PropNameSpecified>Default</PropNameSpecified><PrivateFieldName>StartWithUnderscore</PrivateFieldName><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><EnableExternalSchemasCache>False</EnableExternalSchemasCache><EnableDebug>False</EnableDebug><EnableWarn>False</EnableWarn><ExcludeImportedTypes>False</ExcludeImportedTypes><ExpandNesteadAttributeGroup>False</ExpandNesteadAttributeGroup><CleanupCode>False</CleanupCode><EnableXmlSerialization>False</EnableXmlSerialization><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><EnableEncoding>False</EnableEncoding><EnableXMLIndent>False</EnableXMLIndent><Encoder>UTF8</Encoder><Serializer>XmlSerializer</Serializer><GenerateShouldSerialize>False</GenerateShouldSerialize><BaseClassName>EntityBase</BaseClassName><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ClubCloud.Zimbra.Synchronization
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("CancelPendingRemoteWipeRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "cancelPendingRemoteWipeRequest", Namespace = "urn:zimbraSync")]
    public partial class cancelPendingRemoteWipeRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceId _device;

        public cancelPendingRemoteWipeRequest()
        {
            this._device = new deviceId();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceId device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "deviceId", Namespace = "urn:zimbraSync")]
    public partial class deviceId : System.ComponentModel.INotifyPropertyChanged
    {

        private string _id;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                if (((this._id == null)
                            || (_id.Equals(value) != true)))
                {
                    this._id = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("CancelPendingRemoteWipeResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "cancelPendingRemoteWipeResponse", Namespace = "urn:zimbraSync")]
    public partial class cancelPendingRemoteWipeResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceStatusInfo _device;

        public cancelPendingRemoteWipeResponse()
        {
            this._device = new deviceStatusInfo();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceStatusInfo device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "deviceStatusInfo", Namespace = "urn:zimbraSync")]
    public partial class deviceStatusInfo : System.ComponentModel.INotifyPropertyChanged
    {

        private bool _provisionable;

        private sbyte _status;

        private int _firstReqReceived;

        private System.Nullable<int> _lastPolicyUpdate;

        private System.Nullable<int> _remoteWipeReqTime;

        private System.Nullable<int> _remoteWipeAckTime;

        private string _recoveryPassword;

        private string _lastUsedDate;

        private string _id;

        private string _type;

        private string _ua;

        private string _protocol;

        private string _model;

        private string _imei;

        private string _friendly_name;

        private string _os;

        private string _os_language;

        private string _phone_number;

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool provisionable
        {
            get
            {
                return this._provisionable;
            }
            set
            {
                if ((_provisionable.Equals(value) != true))
                {
                    this._provisionable = value;
                    this.OnPropertyChanged("provisionable");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte status
        {
            get
            {
                return this._status;
            }
            set
            {
                if (((this._status == null)
                            || (_status.Equals(value) != true)))
                {
                    this._status = value;
                    this.OnPropertyChanged("status");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int firstReqReceived
        {
            get
            {
                return this._firstReqReceived;
            }
            set
            {
                if ((_firstReqReceived.Equals(value) != true))
                {
                    this._firstReqReceived = value;
                    this.OnPropertyChanged("firstReqReceived");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lastPolicyUpdate
        {
            get
            {
                if (this._lastPolicyUpdate.HasValue)
                {
                    return this._lastPolicyUpdate.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_lastPolicyUpdate.Equals(value) != true))
                {
                    this._lastPolicyUpdate = value;
                    this.OnPropertyChanged("lastPolicyUpdate");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool lastPolicyUpdateSpecified
        {
            get
            {
                return this._lastPolicyUpdate.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._lastPolicyUpdate = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int remoteWipeReqTime
        {
            get
            {
                if (this._remoteWipeReqTime.HasValue)
                {
                    return this._remoteWipeReqTime.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_remoteWipeReqTime.Equals(value) != true))
                {
                    this._remoteWipeReqTime = value;
                    this.OnPropertyChanged("remoteWipeReqTime");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool remoteWipeReqTimeSpecified
        {
            get
            {
                return this._remoteWipeReqTime.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._remoteWipeReqTime = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int remoteWipeAckTime
        {
            get
            {
                if (this._remoteWipeAckTime.HasValue)
                {
                    return this._remoteWipeAckTime.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_remoteWipeAckTime.Equals(value) != true))
                {
                    this._remoteWipeAckTime = value;
                    this.OnPropertyChanged("remoteWipeAckTime");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool remoteWipeAckTimeSpecified
        {
            get
            {
                return this._remoteWipeAckTime.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._remoteWipeAckTime = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recoveryPassword
        {
            get
            {
                return this._recoveryPassword;
            }
            set
            {
                if (((this._recoveryPassword == null)
                            || (_recoveryPassword.Equals(value) != true)))
                {
                    this._recoveryPassword = value;
                    this.OnPropertyChanged("recoveryPassword");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastUsedDate
        {
            get
            {
                return this._lastUsedDate;
            }
            set
            {
                if (((this._lastUsedDate == null)
                            || (_lastUsedDate.Equals(value) != true)))
                {
                    this._lastUsedDate = value;
                    this.OnPropertyChanged("lastUsedDate");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                if (((this._id == null)
                            || (_id.Equals(value) != true)))
                {
                    this._id = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type
        {
            get
            {
                return this._type;
            }
            set
            {
                if (((this._type == null)
                            || (_type.Equals(value) != true)))
                {
                    this._type = value;
                    this.OnPropertyChanged("type");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ua
        {
            get
            {
                return this._ua;
            }
            set
            {
                if (((this._ua == null)
                            || (_ua.Equals(value) != true)))
                {
                    this._ua = value;
                    this.OnPropertyChanged("ua");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string protocol
        {
            get
            {
                return this._protocol;
            }
            set
            {
                if (((this._protocol == null)
                            || (_protocol.Equals(value) != true)))
                {
                    this._protocol = value;
                    this.OnPropertyChanged("protocol");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model
        {
            get
            {
                return this._model;
            }
            set
            {
                if (((this._model == null)
                            || (_model.Equals(value) != true)))
                {
                    this._model = value;
                    this.OnPropertyChanged("model");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imei
        {
            get
            {
                return this._imei;
            }
            set
            {
                if (((this._imei == null)
                            || (_imei.Equals(value) != true)))
                {
                    this._imei = value;
                    this.OnPropertyChanged("imei");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string friendly_name
        {
            get
            {
                return this._friendly_name;
            }
            set
            {
                if (((this._friendly_name == null)
                            || (_friendly_name.Equals(value) != true)))
                {
                    this._friendly_name = value;
                    this.OnPropertyChanged("friendly_name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string os
        {
            get
            {
                return this._os;
            }
            set
            {
                if (((this._os == null)
                            || (_os.Equals(value) != true)))
                {
                    this._os = value;
                    this.OnPropertyChanged("os");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string os_language
        {
            get
            {
                return this._os_language;
            }
            set
            {
                if (((this._os_language == null)
                            || (_os_language.Equals(value) != true)))
                {
                    this._os_language = value;
                    this.OnPropertyChanged("os_language");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number
        {
            get
            {
                return this._phone_number;
            }
            set
            {
                if (((this._phone_number == null)
                            || (_phone_number.Equals(value) != true)))
                {
                    this._phone_number = value;
                    this.OnPropertyChanged("phone_number");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("GetDeviceStatusRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "getDeviceStatusRequest", Namespace = "urn:zimbraSync")]
    public partial class getDeviceStatusRequest : System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("GetDeviceStatusResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "getDeviceStatusResponse", Namespace = "urn:zimbraSync")]
    public partial class getDeviceStatusResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private List<deviceStatusInfo> _device;

        public getDeviceStatusResponse()
        {
            this._device = new List<deviceStatusInfo>();
        }

        [System.Xml.Serialization.XmlElementAttribute("device")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<deviceStatusInfo> device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("RemoteWipeRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "remoteWipeRequest", Namespace = "urn:zimbraSync")]
    public partial class remoteWipeRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceId _device;

        public remoteWipeRequest()
        {
            this._device = new deviceId();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceId device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("RemoteWipeResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "remoteWipeResponse", Namespace = "urn:zimbraSync")]
    public partial class remoteWipeResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceStatusInfo _device;

        public remoteWipeResponse()
        {
            this._device = new deviceStatusInfo();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceStatusInfo device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("RemoveDeviceRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "removeDeviceRequest", Namespace = "urn:zimbraSync")]
    public partial class removeDeviceRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceId _device;

        public removeDeviceRequest()
        {
            this._device = new deviceId();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceId device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("RemoveDeviceResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "removeDeviceResponse", Namespace = "urn:zimbraSync")]
    public partial class removeDeviceResponse : System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("ResumeDeviceRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "resumeDeviceRequest", Namespace = "urn:zimbraSync")]
    public partial class resumeDeviceRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceId _device;

        public resumeDeviceRequest()
        {
            this._device = new deviceId();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceId device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("ResumeDeviceResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "resumeDeviceResponse", Namespace = "urn:zimbraSync")]
    public partial class resumeDeviceResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceStatusInfo _device;

        public resumeDeviceResponse()
        {
            this._device = new deviceStatusInfo();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceStatusInfo device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("SuspendDeviceRequest", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "suspendDeviceRequest", Namespace = "urn:zimbraSync")]
    public partial class suspendDeviceRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceId _device;

        public suspendDeviceRequest()
        {
            this._device = new deviceId();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceId device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraSync")]
    [System.Xml.Serialization.XmlRootAttribute("SuspendDeviceResponse", Namespace = "urn:zimbraSync", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "suspendDeviceResponse", Namespace = "urn:zimbraSync")]
    public partial class suspendDeviceResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private deviceStatusInfo _device;

        public suspendDeviceResponse()
        {
            this._device = new deviceStatusInfo();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public deviceStatusInfo device
        {
            get
            {
                return this._device;
            }
            set
            {
                if (((this._device == null)
                            || (_device.Equals(value) != true)))
                {
                    this._device = value;
                    this.OnPropertyChanged("device");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore
