//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_Vereniging_InsertUserControl 
    {
        /// <summary>
        /// ClubCloud_Vereniging_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_Vereniging_DataSource;
    
    	/// <summary>
        /// udp_ClubCloud_Vereniging control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::System.Web.UI.UpdatePanel udp_Vereniging;
    
        /// <summary>
        /// Vereniging_Validator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator Vereniging_Validator;
    
    	/// <summary>
        /// Vereniging_Summary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary Vereniging_Summary;
    
        /// <summary>
        /// InsertVerenigingform control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView InsertVerenigingform;
    
    }
}

