//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_LidmaatschapsoortenUserControl 
    {
    
        /// <summary>
        /// udp_Lidmaatschapsoorten control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel udp_Lidmaatschapsoorten;
    
    	/// <summary>
    	/// tmr_loader_Lidmaatschapsoorten control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.Timer tmr_loader_Lidmaatschapsoorten;
            
    	/// <summary>
    	/// pnl_Lidmaatschapsoorten control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.WebControls.Panel pnl_Lidmaatschapsoorten;
    
    	/// <summary>
    	/// udp_Lidmaatschapsoorten_progress control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.UpdateProgress udp_Lidmaatschapsoorten_progress;
    
        /// <summary>
        /// LidmaatschapsoortMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuTemplate LidmaatschapsoortMenu;
    
    	/// <summary>
        /// Lidmaatschapsoort_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Lidmaatschapsoort_Details;
    
        /// <summary>
        /// Lidmaatschappen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Lidmaatschappen;
    
        /// <summary>
        /// ClubCloud_Lidmaatschapsoort_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_Lidmaatschapsoort_DataSource;
    
        /// <summary>
        /// spgvpager_top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_top;
    
        /// <summary>
        /// ClubCloud_Lidmaatschapsoorten_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridView Lidmaatschapsoorten_Grid;
    
        /// <summary>
        /// spgvpager_bottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_bottom;
            
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}

