//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;
    
    public partial class ClubCloudModelContainer : DbContext
    {
    	public ClubCloudModelContainer()
            : this(false) { }
    
        public ClubCloudModelContainer(bool proxyCreationEnabled)
            : base("name=ClubCloudModelContainer")
        {
    				this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.AutoDetectChangesEnabled = true;
    		this.Configuration.UseDatabaseNullSemantics = false;
    		this.Configuration.ValidateOnSaveEnabled = false;
    
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public ClubCloudModelContainer(string connectionString)
          : this(connectionString, false) { }
    	  
        public ClubCloudModelContainer(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    				this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.AutoDetectChangesEnabled = true;
    		this.Configuration.UseDatabaseNullSemantics = false;
    		this.Configuration.ValidateOnSaveEnabled = false;
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public virtual DbSet<ClubCloud_Gebruiker> ClubCloud_Gebruikers { get; set; }
        public virtual DbSet<ClubCloud_Vereniging> ClubCloud_Verenigingen { get; set; }
        public virtual DbSet<ClubCloud_Accomodatie> ClubCloud_Accomodaties { get; set; }
    
        public virtual int HelloWorld(string input, ObjectParameter output)
        {
            var inputParameter = input != null ?
                new ObjectParameter("input", input) :
                new ObjectParameter("input", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("HelloWorld", inputParameter, output);
        }
    }
}
