//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Reservering))]
    [KnownType(typeof(ClubCloud_Baanblok))]
    [KnownType(typeof(ClubCloud_Accomodatie))]
    
    public partial class ClubCloud_Baan : BeheerBaseModel
    {
        public ClubCloud_Baan()
        {
            this.ClubCloud_Reservering = new HashSet<ClubCloud_Reservering>();
        }
    
    	[DataMember]
        private System.Guid _id;
    	public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[DataMember]
        private string _naam;
    	public string Naam 
    	{ 
    		get { return _naam; } 
    		set { SetProperty(ref _naam, value); } 
    	}
    
    	[DataMember]
        private int _nummer;
    	public int Nummer 
    	{ 
    		get { return _nummer; } 
    		set { SetProperty(ref _nummer, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _baanblokId;
    	public Nullable<System.Guid> BaanblokId 
    	{ 
    		get { return _baanblokId; } 
    		set { SetProperty(ref _baanblokId, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _accomodatieId;
    	public Nullable<System.Guid> AccomodatieId 
    	{ 
    		get { return _accomodatieId; } 
    		set { SetProperty(ref _accomodatieId, value); } 
    	}
    
    	[DataMember]
        private string _status;
    	public string Status 
    	{ 
    		get { return _status; } 
    		set { SetProperty(ref _status, value); } 
    	}
    
    	[DataMember]
        private System.DateTime _keuring;
    	public System.DateTime Keuring 
    	{ 
    		get { return _keuring; } 
    		set { SetProperty(ref _keuring, value); } 
    	}
    
    	[DataMember]
        private string _actief;
    	public string Actief 
    	{ 
    		get { return _actief; } 
    		set { SetProperty(ref _actief, value); } 
    	}
    
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering { get; set; }
    	[DataMember]
        public virtual ClubCloud_Baanblok ClubCloud_Baanblok { get; set; }
    	[DataMember]
        public virtual ClubCloud_Accomodatie ClubCloud_Accomodatie { get; set; }
    }
}
