//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Baan))]
    [KnownType(typeof(ClubCloud_Gebruiker))]
    
    public partial class ClubCloud_Reservering
    {
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public Nullable<System.Guid> BaanId { get; set; }
    	[DataMember]
        public System.DateTime Datum { get; set; }
    	[DataMember]
        public System.TimeSpan Tijd { get; set; }
    	[DataMember]
        public System.TimeSpan Duur { get; set; }
    	[DataMember]
        public ReserveringSoort Soort { get; set; }
    	[DataMember]
        public string Beschrijving { get; set; }
    	[DataMember]
        public Nullable<System.Guid> Gebruiker_Een { get; set; }
    	[DataMember]
        public Nullable<System.Guid> Gebruiker_Twee { get; set; }
    	[DataMember]
        public Nullable<System.Guid> Gebruiker_Drie { get; set; }
    	[DataMember]
        public Nullable<System.Guid> Gebruiker_Vier { get; set; }
    	[DataMember]
        public bool Final { get; set; }
    
    	[DataMember]
        public virtual ClubCloud_Baan ClubCloud_Baan { get; set; }
    	[DataMember]
        public virtual ClubCloud_Gebruiker ClubCloud_Gebruiker_Een { get; set; }
    	[DataMember]
        public virtual ClubCloud_Gebruiker ClubCloud_Gebruiker_Twee { get; set; }
    	[DataMember]
        public virtual ClubCloud_Gebruiker ClubCloud_Gebruiker_Drie { get; set; }
    	[DataMember]
        public virtual ClubCloud_Gebruiker ClubCloud_Gebruiker_Vier { get; set; }
    }
}
