//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Baan))]
    
    public partial class ClubCloud_Baanschema
    {
        public ClubCloud_Baanschema()
        {
            this.Beschikbaar = "True";
        }
    
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public Nullable<System.Guid> BaanId { get; set; }
    	[DataMember]
        public string Beschikbaar { get; set; }
    	[DataMember]
        public Days Dag { get; set; }
    	[DataMember]
        public System.TimeSpan DagBegin { get; set; }
    	[DataMember]
        public System.TimeSpan DagEinde { get; set; }
    
    	[DataMember]
        public virtual ClubCloud_Baan ClubCloud_Baan { get; set; }
    }
}
