//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Functionaris))]
    [KnownType(typeof(ClubCloud_Vereniging))]
    [KnownType(typeof(ClubCloud_Regio))]
    
    public partial class ClubCloud_District
    {
        public ClubCloud_District()
        {
            this.ClubCloud_Functionaris = new HashSet<ClubCloud_Functionaris>();
            this.ClubCloud_Vereniging = new HashSet<ClubCloud_Vereniging>();
        }
    
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public string Naam { get; set; }
    	[DataMember]
        public string Beschrijving { get; set; }
    	[DataMember]
        public string Omschrijving { get; set; }
    	[DataMember]
        public Nullable<System.Guid> RegioId { get; set; }
    	[DataMember]
        public string Actief { get; set; }
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Functionaris> ClubCloud_Functionaris { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Vereniging> ClubCloud_Vereniging { get; set; }
    	[DataMember]
        public virtual ClubCloud_Regio ClubCloud_Regio { get; set; }
    }
}
