//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Vereniging))]
    
    public partial class ClubCloud_Accomodatie
    {
        public ClubCloud_Accomodatie()
        {
            this.ClubCloud_Vereniging = new HashSet<ClubCloud_Vereniging>();
        }
    
    	[DataMember]
        public int Id { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public System.Guid mijnknltb_id { get; set; }
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Vereniging> ClubCloud_Vereniging { get; set; }
    }
}
