//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Accomodatie))]
    [KnownType(typeof(ClubCloud_Reservering))]
    [KnownType(typeof(ClubCloud_Baansoort))]
    [KnownType(typeof(ClubCloud_Baanschema))]
    
    public partial class ClubCloud_Baan
    {
        public ClubCloud_Baan()
        {
            this.ClubCloud_Reservering = new HashSet<ClubCloud_Reservering>();
            this.ClubCLoud_Baanschema = new HashSet<ClubCloud_Baanschema>();
        }
    
    	[DataMember]
        public System.Guid Id { get; set; }
    	[DataMember]
        public string Naam { get; set; }
    	[DataMember]
        public int Nummer { get; set; }
    	[DataMember]
        public BaanSoort Baansoort { get; set; }
    	[DataMember]
        public Nullable<System.Guid> AccomodatieId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> BaansoortId { get; set; }
    
    	[DataMember]
        public virtual ClubCloud_Accomodatie ClubCloud_Accomodatie { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering { get; set; }
    	[DataMember]
        public virtual ClubCloud_Baansoort ClubCloud_Baansoort { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Baanschema> ClubCLoud_Baanschema { get; set; }
    }
}
