//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Service.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Sponsor))]
    
    public partial class ClubCloud_Sponsor_Afbeelding : BeheerBaseModel
    {
        public ClubCloud_Sponsor_Afbeelding()
        {
            this.ClubCloud_Sponsor = new HashSet<ClubCloud_Sponsor>();
        }
    
    	[DataMember]
        private System.Guid _id;
    	public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[DataMember]
        private byte[] _afbeelding;
    	public byte[] Afbeelding 
    	{ 
    		get { return _afbeelding; } 
    		set { SetProperty(ref _afbeelding, value); } 
    	}
    
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Sponsor> ClubCloud_Sponsor { get; set; }
    }
}
