//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Runtime.CompilerServices;
    
    [Serializable]
    [KnownType(typeof(ApplicationInfo))]
    [KnownType(typeof(ApplicationProcessorArchitecture))]
    [DataContract(IsReference = true)]
    
    public partial class ApplicationVersion : INotifyPropertyChanged, IDataErrorInfo, INotifyDataErrorInfo
    {
        public ApplicationVersion()
        {
            this.ApplicationProcessorArchitectures = new HashSet<ApplicationProcessorArchitecture>();
        }
    
    	[DataMember]
        public int Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[IgnoreDataMember]
    	private int _id;
    
    	[DataMember]
        public int ApplicationInfoId 
    	{ 
    		get { return _applicationInfoId; } 
    		set { SetProperty(ref _applicationInfoId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private int _applicationInfoId;
    
    	[DataMember]
        public string IdentityName 
    	{ 
    		get { return _identityName; } 
    		set { SetProperty(ref _identityName, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _identityName;
    
    	[DataMember]
        public string Version 
    	{ 
    		get { return _version; } 
    		set { SetProperty(ref _version, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _version;
    
    	[DataMember]
        public string Publisher 
    	{ 
    		get { return _publisher; } 
    		set { SetProperty(ref _publisher, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _publisher;
    
    	[DataMember]
        public string DisplayName 
    	{ 
    		get { return _displayName; } 
    		set { SetProperty(ref _displayName, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _displayName;
    
    	[DataMember]
        public string PublisherDisplayName 
    	{ 
    		get { return _publisherDisplayName; } 
    		set { SetProperty(ref _publisherDisplayName, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _publisherDisplayName;
    
    	[DataMember]
        public string Description 
    	{ 
    		get { return _description; } 
    		set { SetProperty(ref _description, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _description;
    
    	[DataMember]
        public string ProtocolUrl 
    	{ 
    		get { return _protocolUrl; } 
    		set { SetProperty(ref _protocolUrl, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _protocolUrl;
    
    	[DataMember]
        public System.DateTime OperationDate 
    	{ 
    		get { return _operationDate; } 
    		set { SetProperty(ref _operationDate, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.DateTime _operationDate;
    
    
    	
    	//[DataMember]
        [IgnoreDataMember]
    	public virtual ApplicationInfo ApplicationInfo { get; set; }
    	
    	//[DataMember]
        [IgnoreDataMember]
    	public virtual ICollection<ApplicationProcessorArchitecture> ApplicationProcessorArchitectures { get; set; }
    
        public event PropertyChangedEventHandler PropertyChanged;
        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;
    
        private Dictionary<string, string> _errors = new Dictionary<string, string>();
    
        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
            try
            {
                storage = value;
                this.OnPropertyChanged(propertyName);
                return true;
            }
            catch (Exception ex)
            {
                _errors.Add(propertyName, ex.Message);
                return false;
            }
                
        }
    
    
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected void OnErrorsChanged(object sender, DataErrorsChangedEventArgs e = null)
        {
            var eventHandler = this.ErrorsChanged;
            if (eventHandler != null)
            {
                eventHandler(this, e);
            }
        }
    
    	[IgnoreDataMember]
        public string Error
        {
            get
            {
                return string.Empty;
            }
        }
    
    	[IgnoreDataMember]
        public string this[string columnName]
        {
            get
            {
                if (_errors.ContainsKey(columnName))
                    return _errors[columnName];
                return string.Empty;
            }
        }
    
            
        public System.Collections.IEnumerable GetErrors(string propertyName)
        {
            return _errors[propertyName];
        }
    
    	[IgnoreDataMember]
        public bool HasErrors
        {
            get 
            { 
                if(_errors != null)
                    return (_errors.Count > 0);
                return false;
            }
        }
    }
}
