//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Flags]
    public enum BaanSoort : int
    {
    	[EnumMember]
    	Rodebaan = 1,
    	[EnumMember]
    	Oranjebaan = 2,
    	[EnumMember]
    	Minibaan = 3,
    	[EnumMember]
    	Oefenmuur = 4,
    	[EnumMember]
    	Playground = 5,
    	[EnumMember]
    	Onbekend = 0
    }
}
