//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Vereniging))]
    [KnownType(typeof(ClubCloud_Sponsor_Afbeelding))]
    
    public partial class ClubCloud_Sponsor : BeheerBaseModel
    {
    	[DataMember]
        private System.Guid _id;
    	public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[DataMember]
        private System.Guid _verenigingId;
    	public System.Guid VerenigingId 
    	{ 
    		get { return _verenigingId; } 
    		set { SetProperty(ref _verenigingId, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _afbeeldingId;
    	public Nullable<System.Guid> AfbeeldingId 
    	{ 
    		get { return _afbeeldingId; } 
    		set { SetProperty(ref _afbeeldingId, value); } 
    	}
    
    	[DataMember]
        private string _naam;
    	public string Naam 
    	{ 
    		get { return _naam; } 
    		set { SetProperty(ref _naam, value); } 
    	}
    
    	[DataMember]
        private string _tekst;
    	public string Tekst 
    	{ 
    		get { return _tekst; } 
    		set { SetProperty(ref _tekst, value); } 
    	}
    
    
    	[DataMember]
        public virtual ClubCloud_Vereniging ClubCloud_Vereniging { get; set; }
    	[DataMember]
        public virtual ClubCloud_Sponsor_Afbeelding ClubCloud_Sponsor_Afbeelding { get; set; }
    }
}
