//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Runtime.CompilerServices;
    
    [Serializable]
    [KnownType(typeof(ClubCloud_Functionaris))]
    [KnownType(typeof(ClubCloud_Lidmaatschap))]
    [KnownType(typeof(ClubCloud_Address))]
    [KnownType(typeof(ClubCloud_Vereniging))]
    [KnownType(typeof(ClubCloud_Profiel))]
    [KnownType(typeof(ClubCloud_Reservering))]
    [KnownType(typeof(ClubCloud_Setting))]
    [KnownType(typeof(ClubCloud_Nationaliteit))]
    [DataContract(IsReference = true)]
    
    public partial class ClubCloud_Gebruiker : INotifyPropertyChanged, IDataErrorInfo, INotifyDataErrorInfo
    {
        public ClubCloud_Gebruiker()
        {
            this.ClubCloud_Functionaris = new HashSet<ClubCloud_Functionaris>();
            this.ClubCloud_Lidmaatschap = new HashSet<ClubCloud_Lidmaatschap>();
            this.ClubCloud_Address = new HashSet<ClubCloud_Address>();
            this.ClubCloud_Profiel = new HashSet<ClubCloud_Profiel>();
            this.ClubCloud_Reservering_Een = new HashSet<ClubCloud_Reservering>();
            this.ClubCloud_Reservering_Twee = new HashSet<ClubCloud_Reservering>();
            this.ClubCloud_Reservering_Drie = new HashSet<ClubCloud_Reservering>();
            this.ClubCloud_Reservering_Vier = new HashSet<ClubCloud_Reservering>();
            this.ClubCloud_Setting = new HashSet<ClubCloud_Setting>();
        }
    
    	[DataMember]
        public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.Guid _id;
    
    	[DataMember]
        public string Beschrijving 
    	{ 
    		get { return _beschrijving; } 
    		set { SetProperty(ref _beschrijving, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _beschrijving;
    
    	[DataMember]
        public string Bondsnummer 
    	{ 
    		get { return _bondsnummer; } 
    		set { SetProperty(ref _bondsnummer, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _bondsnummer;
    
    	[DataMember]
        public string Roepnaam 
    	{ 
    		get { return _roepnaam; } 
    		set { SetProperty(ref _roepnaam, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _roepnaam;
    
    	[DataMember]
        public string Aanhef 
    	{ 
    		get { return _aanhef; } 
    		set { SetProperty(ref _aanhef, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _aanhef;
    
    	[DataMember]
        public string Voornaam 
    	{ 
    		get { return _voornaam; } 
    		set { SetProperty(ref _voornaam, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _voornaam;
    
    	[DataMember]
        public string Voornamen 
    	{ 
    		get { return _voornamen; } 
    		set { SetProperty(ref _voornamen, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _voornamen;
    
    	[DataMember]
        public string Achtervoegsel 
    	{ 
    		get { return _achtervoegsel; } 
    		set { SetProperty(ref _achtervoegsel, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _achtervoegsel;
    
    	[DataMember]
        public string Tussenvoegsel 
    	{ 
    		get { return _tussenvoegsel; } 
    		set { SetProperty(ref _tussenvoegsel, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _tussenvoegsel;
    
    	[DataMember]
        public string Achternaam 
    	{ 
    		get { return _achternaam; } 
    		set { SetProperty(ref _achternaam, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _achternaam;
    
    	[DataMember]
        public string Voorletters 
    	{ 
    		get { return _voorletters; } 
    		set { SetProperty(ref _voorletters, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _voorletters;
    
    	[DataMember]
        public bool EmailGeheim 
    	{ 
    		get { return _emailGeheim; } 
    		set { SetProperty(ref _emailGeheim, value); } 
    	}
    
    	[IgnoreDataMember]
    	private bool _emailGeheim;
    
    	[DataMember]
        public string EmailKNLTB 
    	{ 
    		get { return _emailKNLTB; } 
    		set { SetProperty(ref _emailKNLTB, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _emailKNLTB;
    
    	[DataMember]
        public string EmailWebSite 
    	{ 
    		get { return _emailWebSite; } 
    		set { SetProperty(ref _emailWebSite, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _emailWebSite;
    
    	[DataMember]
        public string EmailOverig 
    	{ 
    		get { return _emailOverig; } 
    		set { SetProperty(ref _emailOverig, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _emailOverig;
    
    	[DataMember]
        public bool TelefoonGeheim 
    	{ 
    		get { return _telefoonGeheim; } 
    		set { SetProperty(ref _telefoonGeheim, value); } 
    	}
    
    	[IgnoreDataMember]
    	private bool _telefoonGeheim;
    
    	[DataMember]
        public string TelefoonAvond 
    	{ 
    		get { return _telefoonAvond; } 
    		set { SetProperty(ref _telefoonAvond, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _telefoonAvond;
    
    	[DataMember]
        public string TelefoonOverdag 
    	{ 
    		get { return _telefoonOverdag; } 
    		set { SetProperty(ref _telefoonOverdag, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _telefoonOverdag;
    
    	[DataMember]
        public string TelefoonOverig 
    	{ 
    		get { return _telefoonOverig; } 
    		set { SetProperty(ref _telefoonOverig, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _telefoonOverig;
    
    	[DataMember]
        public string Mobiel 
    	{ 
    		get { return _mobiel; } 
    		set { SetProperty(ref _mobiel, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _mobiel;
    
    	[DataMember]
        public string Fax 
    	{ 
    		get { return _fax; } 
    		set { SetProperty(ref _fax, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _fax;
    
    	[DataMember]
        public string BankNummer 
    	{ 
    		get { return _bankNummer; } 
    		set { SetProperty(ref _bankNummer, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _bankNummer;
    
    	[DataMember]
        public string BankIban 
    	{ 
    		get { return _bankIban; } 
    		set { SetProperty(ref _bankIban, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _bankIban;
    
    	[DataMember]
        public string BankPlaats 
    	{ 
    		get { return _bankPlaats; } 
    		set { SetProperty(ref _bankPlaats, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _bankPlaats;
    
    	[DataMember]
        public Nullable<System.DateTime> Geboortedatum 
    	{ 
    		get { return _geboortedatum; } 
    		set { SetProperty(ref _geboortedatum, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.DateTime> _geboortedatum;
    
    	[DataMember]
        public string Geboorteplaats 
    	{ 
    		get { return _geboorteplaats; } 
    		set { SetProperty(ref _geboorteplaats, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _geboorteplaats;
    
    	[DataMember]
        public Nullable<System.DateTime> OverlijdensDatum 
    	{ 
    		get { return _overlijdensDatum; } 
    		set { SetProperty(ref _overlijdensDatum, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.DateTime> _overlijdensDatum;
    
    	[DataMember]
        public bool AddressGeheim 
    	{ 
    		get { return _addressGeheim; } 
    		set { SetProperty(ref _addressGeheim, value); } 
    	}
    
    	[IgnoreDataMember]
    	private bool _addressGeheim;
    
    	[DataMember]
        public Nullable<System.Guid> NationaliteitId 
    	{ 
    		get { return _nationaliteitId; } 
    		set { SetProperty(ref _nationaliteitId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.Guid> _nationaliteitId;
    
    	[DataMember]
        public string Website 
    	{ 
    		get { return _website; } 
    		set { SetProperty(ref _website, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _website;
    
    	[DataMember]
        public string FTPsite 
    	{ 
    		get { return _fTPsite; } 
    		set { SetProperty(ref _fTPsite, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _fTPsite;
    
    	[DataMember]
        public string Actief 
    	{ 
    		get { return _actief; } 
    		set { SetProperty(ref _actief, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _actief;
    
    	[DataMember]
        public string Beroep 
    	{ 
    		get { return _beroep; } 
    		set { SetProperty(ref _beroep, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _beroep;
    
    	[DataMember]
        public bool Kinderen 
    	{ 
    		get { return _kinderen; } 
    		set { SetProperty(ref _kinderen, value); } 
    	}
    
    	[IgnoreDataMember]
    	private bool _kinderen;
    
    	[DataMember]
        public int KinderenAantal 
    	{ 
    		get { return _kinderenAantal; } 
    		set { SetProperty(ref _kinderenAantal, value); } 
    	}
    
    	[IgnoreDataMember]
    	private int _kinderenAantal;
    
    	[DataMember]
        public string Partner 
    	{ 
    		get { return _partner; } 
    		set { SetProperty(ref _partner, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _partner;
    
    	[DataMember]
        public string AanhefBrief 
    	{ 
    		get { return _aanhefBrief; } 
    		set { SetProperty(ref _aanhefBrief, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _aanhefBrief;
    
    	[DataMember]
        public string AanhefAttentie 
    	{ 
    		get { return _aanhefAttentie; } 
    		set { SetProperty(ref _aanhefAttentie, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _aanhefAttentie;
    
    	[DataMember]
        public int FotoId 
    	{ 
    		get { return _fotoId; } 
    		set { SetProperty(ref _fotoId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private int _fotoId;
    
    	[DataMember]
        public Nullable<System.Guid> VerenigingId 
    	{ 
    		get { return _verenigingId; } 
    		set { SetProperty(ref _verenigingId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.Guid> _verenigingId;
    
    	[DataMember]
        public string Volledigenaam 
    	{ 
    		get { return _volledigenaam; } 
    		set { SetProperty(ref _volledigenaam, value); } 
    	}
    
    	[IgnoreDataMember]
    	private string _volledigenaam;
    
    	[DataMember]
        public GeslachtSoort Geslacht 
    	{ 
    		get { return _geslacht; } 
    		set { SetProperty(ref _geslacht, value); } 
    	}
    
    	[IgnoreDataMember]
    	private GeslachtSoort _geslacht;
    
    	[DataMember]
        public System.DateTime Gewijzigd 
    	{ 
    		get { return _gewijzigd; } 
    		set { SetProperty(ref _gewijzigd, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.DateTime _gewijzigd;
    
    
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Functionaris> ClubCloud_Functionaris { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Lidmaatschap> ClubCloud_Lidmaatschap { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Address> ClubCloud_Address { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ClubCloud_Vereniging ClubCloud_Vereniging { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Profiel> ClubCloud_Profiel { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering_Een { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering_Twee { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering_Drie { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Reservering> ClubCloud_Reservering_Vier { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ICollection<ClubCloud_Setting> ClubCloud_Setting { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ClubCloud_Nationaliteit ClubCloud_Nationaliteit { get; set; }
    
        public event PropertyChangedEventHandler PropertyChanged;
        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;
    
        private Dictionary<string, string> _errors = new Dictionary<string, string>();
    
        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
            try
            {
                storage = value;
                this.OnPropertyChanged(propertyName);
                return true;
            }
            catch (Exception ex)
            {
                _errors.Add(propertyName, ex.Message);
                return false;
            }
                
        }
    
    
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	[IgnoreDataMember]
        public string Error
        {
            get
            {
                return string.Empty;
            }
        }
    
    	[IgnoreDataMember]
        public string this[string columnName]
        {
            get
            {
                if (_errors.ContainsKey(columnName))
                    return _errors[columnName];
                return string.Empty;
            }
        }
    
            
        public System.Collections.IEnumerable GetErrors(string propertyName)
        {
            return _errors[propertyName];
        }
    
    	[IgnoreDataMember]
        public bool HasErrors
        {
            get 
            { 
                if(_errors != null)
                    return (_errors.Count > 0);
                return false;
            }
        }
    }
}
