//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    using System.ComponentModel;
    using System.Runtime.CompilerServices;
    
    [Serializable]
    [KnownType(typeof(ClubCloud_Baan))]
    [KnownType(typeof(ClubCloud_Vereniging))]
    [DataContract(IsReference = true)]
    
    public partial class ClubCloud_Baanschema : INotifyPropertyChanged, IDataErrorInfo, INotifyDataErrorInfo
    {
    	[DataMember]
        public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.Guid _id;
    
    	[DataMember]
        public Nullable<System.Guid> BaanId 
    	{ 
    		get { return _baanId; } 
    		set { SetProperty(ref _baanId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.Guid> _baanId;
    
    	[DataMember]
        public Nullable<System.Guid> VerenigingId 
    	{ 
    		get { return _verenigingId; } 
    		set { SetProperty(ref _verenigingId, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Nullable<System.Guid> _verenigingId;
    
    	[DataMember]
        public bool Beschikbaar 
    	{ 
    		get { return _beschikbaar; } 
    		set { SetProperty(ref _beschikbaar, value); } 
    	}
    
    	[IgnoreDataMember]
    	private bool _beschikbaar;
    
    	[DataMember]
        public Month MaandBegin 
    	{ 
    		get { return _maandBegin; } 
    		set { SetProperty(ref _maandBegin, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Month _maandBegin;
    
    	[DataMember]
        public Month MaandEinde 
    	{ 
    		get { return _maandEinde; } 
    		set { SetProperty(ref _maandEinde, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Month _maandEinde;
    
    	[DataMember]
        public Days Dag 
    	{ 
    		get { return _dag; } 
    		set { SetProperty(ref _dag, value); } 
    	}
    
    	[IgnoreDataMember]
    	private Days _dag;
    
    	[DataMember]
        public System.TimeSpan DagBegin 
    	{ 
    		get { return _dagBegin; } 
    		set { SetProperty(ref _dagBegin, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.TimeSpan _dagBegin;
    
    	[DataMember]
        public System.TimeSpan DagEinde 
    	{ 
    		get { return _dagEinde; } 
    		set { SetProperty(ref _dagEinde, value); } 
    	}
    
    	[IgnoreDataMember]
    	private System.TimeSpan _dagEinde;
    
    
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ClubCloud_Baan ClubCloud_Baan { get; set; }
    
    	//[DataMember]
    	[IgnoreDataMember]
        public virtual ClubCloud_Vereniging ClubCloud_Vereniging { get; set; }
    
        public event PropertyChangedEventHandler PropertyChanged;
        public event EventHandler<DataErrorsChangedEventArgs> ErrorsChanged;
    
        private Dictionary<string, string> _errors = new Dictionary<string, string>();
    
        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] String propertyName = null)
        {
            if (object.Equals(storage, value)) return false;
    
            try
            {
                storage = value;
                this.OnPropertyChanged(propertyName);
                return true;
            }
            catch (Exception ex)
            {
                _errors.Add(propertyName, ex.Message);
                return false;
            }
                
        }
    
    
        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            var eventHandler = this.PropertyChanged;
            if (eventHandler != null)
            {
                eventHandler(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
    	[IgnoreDataMember]
        public string Error
        {
            get
            {
                return string.Empty;
            }
        }
    
    	[IgnoreDataMember]
        public string this[string columnName]
        {
            get
            {
                if (_errors.ContainsKey(columnName))
                    return _errors[columnName];
                return string.Empty;
            }
        }
    
            
        public System.Collections.IEnumerable GetErrors(string propertyName)
        {
            return _errors[propertyName];
        }
    
    	[IgnoreDataMember]
        public bool HasErrors
        {
            get 
            { 
                if(_errors != null)
                    return (_errors.Count > 0);
                return false;
            }
        }
    }
}
