//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Functionaris))]
    [KnownType(typeof(ClubCloud_Vereniging))]
    [KnownType(typeof(ClubCloud_Regio))]
    [KnownType(typeof(ClubCloud_Accommodatie))]
    
    public partial class ClubCloud_District : BeheerBaseModel
    {
        public ClubCloud_District()
        {
            this.ClubCloud_Functionaris = new HashSet<ClubCloud_Functionaris>();
            this.ClubCloud_Vereniging = new HashSet<ClubCloud_Vereniging>();
            this.ClubCloud_Accommodatie = new HashSet<ClubCloud_Accommodatie>();
        }
    
    	[DataMember]
        private System.Guid _id;
    	public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[DataMember]
        private string _naam;
    	public string Naam 
    	{ 
    		get { return _naam; } 
    		set { SetProperty(ref _naam, value); } 
    	}
    
    	[DataMember]
        private string _beschrijving;
    	public string Beschrijving 
    	{ 
    		get { return _beschrijving; } 
    		set { SetProperty(ref _beschrijving, value); } 
    	}
    
    	[DataMember]
        private string _omschrijving;
    	public string Omschrijving 
    	{ 
    		get { return _omschrijving; } 
    		set { SetProperty(ref _omschrijving, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _regioId;
    	public Nullable<System.Guid> RegioId 
    	{ 
    		get { return _regioId; } 
    		set { SetProperty(ref _regioId, value); } 
    	}
    
    	[DataMember]
        private string _actief;
    	public string Actief 
    	{ 
    		get { return _actief; } 
    		set { SetProperty(ref _actief, value); } 
    	}
    
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Functionaris> ClubCloud_Functionaris { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Vereniging> ClubCloud_Vereniging { get; set; }
    	[DataMember]
        public virtual ClubCloud_Regio ClubCloud_Regio { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Accommodatie> ClubCloud_Accommodatie { get; set; }
    }
}
