//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [Serializable]
    [DataContract(IsReference = true)]
    [KnownType(typeof(ClubCloud_Functionaris))]
    [KnownType(typeof(ClubCloud_Lidmaatschap))]
    [KnownType(typeof(ClubCloud_Bestuursorgaan))]
    [KnownType(typeof(ClubCloud_District))]
    [KnownType(typeof(ClubCloud_Rechtsvorm))]
    [KnownType(typeof(ClubCloud_Accommodatie))]
    [KnownType(typeof(ClubCloud_Address))]
    [KnownType(typeof(ClubCloud_Regio))]
    [KnownType(typeof(ClubCloud_Gebruiker))]
    [KnownType(typeof(ClubCloud_Afhang))]
    [KnownType(typeof(ClubCloud_Sponsor))]
    
    public partial class ClubCloud_Vereniging : BeheerBaseModel
    {
        public ClubCloud_Vereniging()
        {
            this.ClubCloud_Functionaris = new HashSet<ClubCloud_Functionaris>();
            this.ClubCloud_Lidmaatschap = new HashSet<ClubCloud_Lidmaatschap>();
            this.ClubCloud_Bestuursorgaan = new HashSet<ClubCloud_Bestuursorgaan>();
            this.ClubCloud_Address = new HashSet<ClubCloud_Address>();
            this.ClubCloud_Gebruiker = new HashSet<ClubCloud_Gebruiker>();
            this.ClubCloud_Afhangen = new HashSet<ClubCloud_Afhang>();
            this.ClubCloud_Sponsor = new HashSet<ClubCloud_Sponsor>();
        }
    
    	[DataMember]
        private System.Guid _id;
    	public System.Guid Id 
    	{ 
    		get { return _id; } 
    		set { SetProperty(ref _id, value); } 
    	}
    
    	[DataMember]
        private string _naam;
    	public string Naam 
    	{ 
    		get { return _naam; } 
    		set { SetProperty(ref _naam, value); } 
    	}
    
    	[DataMember]
        private string _beschrijving;
    	public string Beschrijving 
    	{ 
    		get { return _beschrijving; } 
    		set { SetProperty(ref _beschrijving, value); } 
    	}
    
    	[DataMember]
        private string _nummer;
    	public string Nummer 
    	{ 
    		get { return _nummer; } 
    		set { SetProperty(ref _nummer, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _districtId;
    	public Nullable<System.Guid> DistrictId 
    	{ 
    		get { return _districtId; } 
    		set { SetProperty(ref _districtId, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _rechtsvormId;
    	public Nullable<System.Guid> RechtsvormId 
    	{ 
    		get { return _rechtsvormId; } 
    		set { SetProperty(ref _rechtsvormId, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _accommodatieId;
    	public Nullable<System.Guid> AccommodatieId 
    	{ 
    		get { return _accommodatieId; } 
    		set { SetProperty(ref _accommodatieId, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.Guid> _regioId;
    	public Nullable<System.Guid> RegioId 
    	{ 
    		get { return _regioId; } 
    		set { SetProperty(ref _regioId, value); } 
    	}
    
    	[DataMember]
        private string _bankNummer;
    	public string BankNummer 
    	{ 
    		get { return _bankNummer; } 
    		set { SetProperty(ref _bankNummer, value); } 
    	}
    
    	[DataMember]
        private string _bankIban;
    	public string BankIban 
    	{ 
    		get { return _bankIban; } 
    		set { SetProperty(ref _bankIban, value); } 
    	}
    
    	[DataMember]
        private string _bankPlaats;
    	public string BankPlaats 
    	{ 
    		get { return _bankPlaats; } 
    		set { SetProperty(ref _bankPlaats, value); } 
    	}
    
    	[DataMember]
        private string _kvKnummer;
    	public string KvKnummer 
    	{ 
    		get { return _kvKnummer; } 
    		set { SetProperty(ref _kvKnummer, value); } 
    	}
    
    	[DataMember]
        private string _kvKplaats;
    	public string KvKplaats 
    	{ 
    		get { return _kvKplaats; } 
    		set { SetProperty(ref _kvKplaats, value); } 
    	}
    
    	[DataMember]
        private string _emailKNLTB;
    	public string EmailKNLTB 
    	{ 
    		get { return _emailKNLTB; } 
    		set { SetProperty(ref _emailKNLTB, value); } 
    	}
    
    	[DataMember]
        private string _emailWebSite;
    	public string EmailWebSite 
    	{ 
    		get { return _emailWebSite; } 
    		set { SetProperty(ref _emailWebSite, value); } 
    	}
    
    	[DataMember]
        private string _emailOverig;
    	public string EmailOverig 
    	{ 
    		get { return _emailOverig; } 
    		set { SetProperty(ref _emailOverig, value); } 
    	}
    
    	[DataMember]
        private string _fax;
    	public string Fax 
    	{ 
    		get { return _fax; } 
    		set { SetProperty(ref _fax, value); } 
    	}
    
    	[DataMember]
        private string _telefoonAvond;
    	public string TelefoonAvond 
    	{ 
    		get { return _telefoonAvond; } 
    		set { SetProperty(ref _telefoonAvond, value); } 
    	}
    
    	[DataMember]
        private string _telefoonOverdag;
    	public string TelefoonOverdag 
    	{ 
    		get { return _telefoonOverdag; } 
    		set { SetProperty(ref _telefoonOverdag, value); } 
    	}
    
    	[DataMember]
        private string _telefoonOverig;
    	public string TelefoonOverig 
    	{ 
    		get { return _telefoonOverig; } 
    		set { SetProperty(ref _telefoonOverig, value); } 
    	}
    
    	[DataMember]
        private string _website;
    	public string Website 
    	{ 
    		get { return _website; } 
    		set { SetProperty(ref _website, value); } 
    	}
    
    	[DataMember]
        private string _fTPsite;
    	public string FTPsite 
    	{ 
    		get { return _fTPsite; } 
    		set { SetProperty(ref _fTPsite, value); } 
    	}
    
    	[DataMember]
        private string _actief;
    	public string Actief 
    	{ 
    		get { return _actief; } 
    		set { SetProperty(ref _actief, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.DateTime> _oprichting;
    	public Nullable<System.DateTime> Oprichting 
    	{ 
    		get { return _oprichting; } 
    		set { SetProperty(ref _oprichting, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.DateTime> _erkenning;
    	public Nullable<System.DateTime> Erkenning 
    	{ 
    		get { return _erkenning; } 
    		set { SetProperty(ref _erkenning, value); } 
    	}
    
    	[DataMember]
        private Nullable<System.DateTime> _gestopt;
    	public Nullable<System.DateTime> Gestopt 
    	{ 
    		get { return _gestopt; } 
    		set { SetProperty(ref _gestopt, value); } 
    	}
    
    	[DataMember]
        private int _maanden;
    	public int Maanden 
    	{ 
    		get { return _maanden; } 
    		set { SetProperty(ref _maanden, value); } 
    	}
    
    	[DataMember]
        private System.DateTime _gewijzigd;
    	public System.DateTime Gewijzigd 
    	{ 
    		get { return _gewijzigd; } 
    		set { SetProperty(ref _gewijzigd, value); } 
    	}
    
    
    	[DataMember]
        public virtual ICollection<ClubCloud_Functionaris> ClubCloud_Functionaris { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Lidmaatschap> ClubCloud_Lidmaatschap { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Bestuursorgaan> ClubCloud_Bestuursorgaan { get; set; }
    	[DataMember]
        public virtual ClubCloud_District ClubCloud_District { get; set; }
    	[DataMember]
        public virtual ClubCloud_Rechtsvorm ClubCloud_Rechtsvorm { get; set; }
    	[DataMember]
        public virtual ClubCloud_Accommodatie ClubCloud_Accommodatie { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Address> ClubCloud_Address { get; set; }
    	[DataMember]
        public virtual ClubCloud_Regio ClubCloud_Regio { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Gebruiker> ClubCloud_Gebruiker { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Afhang> ClubCloud_Afhangen { get; set; }
    	[DataMember]
        public virtual ICollection<ClubCloud_Sponsor> ClubCloud_Sponsor { get; set; }
    }
}
