//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    
    [Flags]
    public enum Financieel : int
    {
        None = 0,
        Machtiging = 1,
        iDEAL = 2,
        PayPal = 4,
        Factuur = 8
    }
}
