//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    [Flags]
    public enum Financieel : int
    {
    	[EnumMember]
    	None = 0,
    	[EnumMember]
    	Machtiging = 1,
    	[EnumMember]
    	iDEAL = 2,
    	[EnumMember]
    	PayPal = 4,
    	[EnumMember]
    	Factuur = 8
    }
}
