//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Collections.Generic;
    
    public partial class JournalEntry
    {
        public JournalEntry()
        {
            this.JournalTransactions = new HashSet<JournalTransaction>();
        }
    
    	[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public System.Guid Id { get; set; }
    	
        public string Name { get; set; }
    	
        public string Description { get; set; }
    	
        public string Date { get; set; }
    	
        public string Number { get; set; }
    	
        public System.Guid LedgerId { get; set; }
    	
        public System.Guid JournalId { get; set; }
    	
        public Nullable<System.Guid> InvoiceId { get; set; }
    	
        public System.Guid JournalYearId { get; set; }
    	
        public System.Guid CostCenterId { get; set; }
    
        public virtual Journal Journal { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual ICollection<JournalTransaction> JournalTransactions { get; set; }
        public virtual JournalYear JournalYear { get; set; }
        public virtual Ledger Ledger { get; set; }
        public virtual CostCenter CostCenter { get; set; }
    }
}
