//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Model
{
    using System;
    using System.Runtime.Serialization;
    
    [Flags]
    public enum Month : int
    {
        januari = 1,
        februari = 2,
        maart = 3,
        april = 4,
        mei = 5,
        juni = 6,
        juli = 7,
        augustus = 8,
        september = 9,
        oktober = 10,
        november = 11,
        december = 12
    }
}
