//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_BestuursorganenUserControl 
    {
    
        /// <summary>
        /// udp_Bestuursorganen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel udp_Bestuursorganen;
    
    	/// <summary>
    	/// tmr_loader_Bestuursorganen control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.Timer tmr_loader_Bestuursorganen;
            
    	/// <summary>
    	/// pnl_Bestuursorganen control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.WebControls.Panel pnl_Bestuursorganen;
    
    	/// <summary>
    	/// udp_Bestuursorganen_progress control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.UpdateProgress udp_Bestuursorganen_progress;
    
        /// <summary>
        /// BestuursorgaanMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuTemplate BestuursorgaanMenu;
    
    	/// <summary>
        /// Bestuursorgaan_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Bestuursorgaan_Details;
    
        /// <summary>
        /// Functionarissen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate Functionarissen;
    
        /// <summary>
        /// ClubCloud_Bestuursorgaan_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_Bestuursorgaan_DataSource;
    
        /// <summary>
        /// spgvpager_top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_top;
    
        /// <summary>
        /// ClubCloud_Bestuursorganen_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridView Bestuursorganen_Grid;
    
        /// <summary>
        /// spgvpager_bottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_bottom;
            
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}

