//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_BanenSpeciaalUserControl 
    {
    
        /// <summary>
        /// udp_BanenSpeciaal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel udp_BanenSpeciaal;
    
    	/// <summary>
    	/// tmr_loader_BanenSpeciaal control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.Timer tmr_loader_BanenSpeciaal;
            
    	/// <summary>
    	/// pnl_BanenSpeciaal control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.WebControls.Panel pnl_BanenSpeciaal;
    
    	/// <summary>
    	/// udp_BanenSpeciaal_progress control.
    	/// </summary>
    	/// <remarks>
    	/// Auto-generated field.
    	/// To modify move field declaration from designer file to code-behind file.
    	/// </remarks>
    	protected global::System.Web.UI.UpdateProgress udp_BanenSpeciaal_progress;
    
        /// <summary>
        /// BaanSpeciaalMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuTemplate BaanSpeciaalMenu;
    
    	/// <summary>
        /// BaanSpeciaal_Details control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.MenuItemTemplate BaanSpeciaal_Details;
    
        /// <summary>
        /// ClubCloud_BaanSpeciaal_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_BaanSpeciaal_DataSource;
    
        /// <summary>
        /// spgvpager_top control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_top;
    
        /// <summary>
        /// ClubCloud_BanenSpeciaal_Grid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridView BanenSpeciaal_Grid;
    
        /// <summary>
        /// spgvpager_bottom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Microsoft.SharePoint.WebControls.SPGridViewPager spgvpager_bottom;
            
        /// <summary>
        /// lblMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}

