// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.0.0.285
//    <NameSpace>ClubCloud.Zimbra.Administration.Extended</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>True</EnableDataBinding><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net45</CodeBaseTag><InitializeFields>All</InitializeFields><GenerateUnusedComplexTypes>False</GenerateUnusedComplexTypes><GenerateUnusedSimpleTypes>False</GenerateUnusedSimpleTypes><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>True</OrderXMLAttrib><EnableLazyLoading>False</EnableLazyLoading><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><AutomaticProperties>False</AutomaticProperties><PropNameSpecified>Default</PropNameSpecified><PrivateFieldName>StartWithUnderscore</PrivateFieldName><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><EnableExternalSchemasCache>False</EnableExternalSchemasCache><EnableDebug>False</EnableDebug><EnableWarn>False</EnableWarn><ExcludeImportedTypes>False</ExcludeImportedTypes><ExpandNesteadAttributeGroup>False</ExpandNesteadAttributeGroup><CleanupCode>False</CleanupCode><EnableXmlSerialization>False</EnableXmlSerialization><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><EnableEncoding>False</EnableEncoding><EnableXMLIndent>False</EnableXMLIndent><Encoder>UTF8</Encoder><Serializer>XmlSerializer</Serializer><GenerateShouldSerialize>False</GenerateShouldSerialize><BaseClassName>EntityBase</BaseClassName><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><CustomUsings></CustomUsings>
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace ClubCloud.Zimbra.Administration.Extended
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("BulkIMAPDataImportRequest", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bulkIMAPDataImportRequest", Namespace = "urn:zimbraAdminExt")]
    public partial class bulkIMAPDataImportRequest : System.ComponentModel.INotifyPropertyChanged
    {

        private string _sourceType;

        private string _aid;

        private List<name> _account;

        private string _connectionType;

        private string _sourceServerType;

        private string _iMAPHost;

        private string _iMAPPort;

        private string _indexBatchSize;

        private string _useAdminLogin;

        private string _iMAPAdminLogin;

        private string _iMAPAdminPassword;

        private string _op;

        public bulkIMAPDataImportRequest()
        {
            this._account = new List<name>();
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceType
        {
            get
            {
                return this._sourceType;
            }
            set
            {
                if (((this._sourceType == null)
                            || (_sourceType.Equals(value) != true)))
                {
                    this._sourceType = value;
                    this.OnPropertyChanged("sourceType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aid
        {
            get
            {
                return this._aid;
            }
            set
            {
                if (((this._aid == null)
                            || (_aid.Equals(value) != true)))
                {
                    this._aid = value;
                    this.OnPropertyChanged("aid");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("account")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<name> account
        {
            get
            {
                return this._account;
            }
            set
            {
                if (((this._account == null)
                            || (_account.Equals(value) != true)))
                {
                    this._account = value;
                    this.OnPropertyChanged("account");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionType
        {
            get
            {
                return this._connectionType;
            }
            set
            {
                if (((this._connectionType == null)
                            || (_connectionType.Equals(value) != true)))
                {
                    this._connectionType = value;
                    this.OnPropertyChanged("ConnectionType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceServerType
        {
            get
            {
                return this._sourceServerType;
            }
            set
            {
                if (((this._sourceServerType == null)
                            || (_sourceServerType.Equals(value) != true)))
                {
                    this._sourceServerType = value;
                    this.OnPropertyChanged("sourceServerType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPHost
        {
            get
            {
                return this._iMAPHost;
            }
            set
            {
                if (((this._iMAPHost == null)
                            || (_iMAPHost.Equals(value) != true)))
                {
                    this._iMAPHost = value;
                    this.OnPropertyChanged("IMAPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPPort
        {
            get
            {
                return this._iMAPPort;
            }
            set
            {
                if (((this._iMAPPort == null)
                            || (_iMAPPort.Equals(value) != true)))
                {
                    this._iMAPPort = value;
                    this.OnPropertyChanged("IMAPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string indexBatchSize
        {
            get
            {
                return this._indexBatchSize;
            }
            set
            {
                if (((this._indexBatchSize == null)
                            || (_indexBatchSize.Equals(value) != true)))
                {
                    this._indexBatchSize = value;
                    this.OnPropertyChanged("indexBatchSize");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UseAdminLogin
        {
            get
            {
                return this._useAdminLogin;
            }
            set
            {
                if (((this._useAdminLogin == null)
                            || (_useAdminLogin.Equals(value) != true)))
                {
                    this._useAdminLogin = value;
                    this.OnPropertyChanged("UseAdminLogin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPAdminLogin
        {
            get
            {
                return this._iMAPAdminLogin;
            }
            set
            {
                if (((this._iMAPAdminLogin == null)
                            || (_iMAPAdminLogin.Equals(value) != true)))
                {
                    this._iMAPAdminLogin = value;
                    this.OnPropertyChanged("IMAPAdminLogin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPAdminPassword
        {
            get
            {
                return this._iMAPAdminPassword;
            }
            set
            {
                if (((this._iMAPAdminPassword == null)
                            || (_iMAPAdminPassword.Equals(value) != true)))
                {
                    this._iMAPAdminPassword = value;
                    this.OnPropertyChanged("IMAPAdminPassword");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string op
        {
            get
            {
                return this._op;
            }
            set
            {
                if (((this._op == null)
                            || (_op.Equals(value) != true)))
                {
                    this._op = value;
                    this.OnPropertyChanged("op");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "name", Namespace = "urn:zimbraAdminExt")]
    public partial class name : System.ComponentModel.INotifyPropertyChanged
    {

        private string _name1;

        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name1
        {
            get
            {
                return this._name1;
            }
            set
            {
                if (((this._name1 == null)
                            || (_name1.Equals(value) != true)))
                {
                    this._name1 = value;
                    this.OnPropertyChanged("name1");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("BulkIMAPDataImportResponse", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bulkIMAPDataImportResponse", Namespace = "urn:zimbraAdminExt")]
    public partial class bulkIMAPDataImportResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private List<nameId> _runningAccounts;

        private System.Nullable<int> _totalCount;

        private System.Nullable<int> _idleCount;

        private System.Nullable<int> _runningCount;

        private System.Nullable<int> _finishedCount;

        private string _connectionType;

        private string _iMAPHost;

        private string _iMAPPort;

        private string _indexBatchSize;

        private System.Nullable<int> _useAdminLogin;

        private string _iMAPAdminLogin;

        private string _iMAPAdminPassword;

        public bulkIMAPDataImportResponse()
        {
            this._runningAccounts = new List<nameId>();
        }

        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("account", IsNullable = false)]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<nameId> runningAccounts
        {
            get
            {
                return this._runningAccounts;
            }
            set
            {
                if (((this._runningAccounts == null)
                            || (_runningAccounts.Equals(value) != true)))
                {
                    this._runningAccounts = value;
                    this.OnPropertyChanged("runningAccounts");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalCount
        {
            get
            {
                if (this._totalCount.HasValue)
                {
                    return this._totalCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_totalCount.Equals(value) != true))
                {
                    this._totalCount = value;
                    this.OnPropertyChanged("totalCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool totalCountSpecified
        {
            get
            {
                return this._totalCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._totalCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idleCount
        {
            get
            {
                if (this._idleCount.HasValue)
                {
                    return this._idleCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_idleCount.Equals(value) != true))
                {
                    this._idleCount = value;
                    this.OnPropertyChanged("idleCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool idleCountSpecified
        {
            get
            {
                return this._idleCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._idleCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int runningCount
        {
            get
            {
                if (this._runningCount.HasValue)
                {
                    return this._runningCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_runningCount.Equals(value) != true))
                {
                    this._runningCount = value;
                    this.OnPropertyChanged("runningCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool runningCountSpecified
        {
            get
            {
                return this._runningCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._runningCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int finishedCount
        {
            get
            {
                if (this._finishedCount.HasValue)
                {
                    return this._finishedCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_finishedCount.Equals(value) != true))
                {
                    this._finishedCount = value;
                    this.OnPropertyChanged("finishedCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool finishedCountSpecified
        {
            get
            {
                return this._finishedCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._finishedCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionType
        {
            get
            {
                return this._connectionType;
            }
            set
            {
                if (((this._connectionType == null)
                            || (_connectionType.Equals(value) != true)))
                {
                    this._connectionType = value;
                    this.OnPropertyChanged("ConnectionType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPHost
        {
            get
            {
                return this._iMAPHost;
            }
            set
            {
                if (((this._iMAPHost == null)
                            || (_iMAPHost.Equals(value) != true)))
                {
                    this._iMAPHost = value;
                    this.OnPropertyChanged("IMAPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPPort
        {
            get
            {
                return this._iMAPPort;
            }
            set
            {
                if (((this._iMAPPort == null)
                            || (_iMAPPort.Equals(value) != true)))
                {
                    this._iMAPPort = value;
                    this.OnPropertyChanged("IMAPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string indexBatchSize
        {
            get
            {
                return this._indexBatchSize;
            }
            set
            {
                if (((this._indexBatchSize == null)
                            || (_indexBatchSize.Equals(value) != true)))
                {
                    this._indexBatchSize = value;
                    this.OnPropertyChanged("indexBatchSize");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UseAdminLogin
        {
            get
            {
                if (this._useAdminLogin.HasValue)
                {
                    return this._useAdminLogin.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_useAdminLogin.Equals(value) != true))
                {
                    this._useAdminLogin = value;
                    this.OnPropertyChanged("UseAdminLogin");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool UseAdminLoginSpecified
        {
            get
            {
                return this._useAdminLogin.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._useAdminLogin = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPAdminLogin
        {
            get
            {
                return this._iMAPAdminLogin;
            }
            set
            {
                if (((this._iMAPAdminLogin == null)
                            || (_iMAPAdminLogin.Equals(value) != true)))
                {
                    this._iMAPAdminLogin = value;
                    this.OnPropertyChanged("IMAPAdminLogin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAPAdminPassword
        {
            get
            {
                return this._iMAPAdminPassword;
            }
            set
            {
                if (((this._iMAPAdminPassword == null)
                            || (_iMAPAdminPassword.Equals(value) != true)))
                {
                    this._iMAPAdminPassword = value;
                    this.OnPropertyChanged("IMAPAdminPassword");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "nameId", Namespace = "urn:zimbraAdminExt")]
    public partial class nameId : System.ComponentModel.INotifyPropertyChanged
    {

        private string _name;

        private string _id;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                if (((this._name == null)
                            || (_name.Equals(value) != true)))
                {
                    this._name = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this._id;
            }
            set
            {
                if (((this._id == null)
                            || (_id.Equals(value) != true)))
                {
                    this._id = value;
                    this.OnPropertyChanged("id");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("BulkImportAccountsRequest", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bulkImportAccountsRequest", Namespace = "urn:zimbraAdminExt")]
    public partial class bulkImportAccountsRequest : attrsImpl
    {

        private string _createDomains;

        private string _sMTPHost;

        private string _sMTPPort;

        private string _sourceType;

        private string _aid;

        private string _password;

        private System.Nullable<int> _genPasswordLength;

        private string _generatePassword;

        private System.Nullable<int> _maxResults;

        private string _mustChangePassword;

        private string _op;

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createDomains
        {
            get
            {
                return this._createDomains;
            }
            set
            {
                if (((this._createDomains == null)
                            || (_createDomains.Equals(value) != true)))
                {
                    this._createDomains = value;
                    this.OnPropertyChanged("createDomains");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPHost
        {
            get
            {
                return this._sMTPHost;
            }
            set
            {
                if (((this._sMTPHost == null)
                            || (_sMTPHost.Equals(value) != true)))
                {
                    this._sMTPHost = value;
                    this.OnPropertyChanged("SMTPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPPort
        {
            get
            {
                return this._sMTPPort;
            }
            set
            {
                if (((this._sMTPPort == null)
                            || (_sMTPPort.Equals(value) != true)))
                {
                    this._sMTPPort = value;
                    this.OnPropertyChanged("SMTPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sourceType
        {
            get
            {
                return this._sourceType;
            }
            set
            {
                if (((this._sourceType == null)
                            || (_sourceType.Equals(value) != true)))
                {
                    this._sourceType = value;
                    this.OnPropertyChanged("sourceType");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aid
        {
            get
            {
                return this._aid;
            }
            set
            {
                if (((this._aid == null)
                            || (_aid.Equals(value) != true)))
                {
                    this._aid = value;
                    this.OnPropertyChanged("aid");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                if (((this._password == null)
                            || (_password.Equals(value) != true)))
                {
                    this._password = value;
                    this.OnPropertyChanged("password");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genPasswordLength
        {
            get
            {
                if (this._genPasswordLength.HasValue)
                {
                    return this._genPasswordLength.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_genPasswordLength.Equals(value) != true))
                {
                    this._genPasswordLength = value;
                    this.OnPropertyChanged("genPasswordLength");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool genPasswordLengthSpecified
        {
            get
            {
                return this._genPasswordLength.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._genPasswordLength = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string generatePassword
        {
            get
            {
                return this._generatePassword;
            }
            set
            {
                if (((this._generatePassword == null)
                            || (_generatePassword.Equals(value) != true)))
                {
                    this._generatePassword = value;
                    this.OnPropertyChanged("generatePassword");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxResults
        {
            get
            {
                if (this._maxResults.HasValue)
                {
                    return this._maxResults.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_maxResults.Equals(value) != true))
                {
                    this._maxResults = value;
                    this.OnPropertyChanged("maxResults");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxResultsSpecified
        {
            get
            {
                return this._maxResults.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._maxResults = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mustChangePassword
        {
            get
            {
                return this._mustChangePassword;
            }
            set
            {
                if (((this._mustChangePassword == null)
                            || (_mustChangePassword.Equals(value) != true)))
                {
                    this._mustChangePassword = value;
                    this.OnPropertyChanged("mustChangePassword");
                }
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string op
        {
            get
            {
                return this._op;
            }
            set
            {
                if (((this._op == null)
                            || (_op.Equals(value) != true)))
                {
                    this._op = value;
                    this.OnPropertyChanged("op");
                }
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bulkIMAPImportTaskInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(generateBulkProvisionFileFromLDAPRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(bulkImportAccountsRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "attrsImpl", Namespace = "urn:zimbraAdminExt")]
    public abstract partial class attrsImpl : System.ComponentModel.INotifyPropertyChanged
    {

        private List<attr> _a;

        public attrsImpl()
        {
            this._a = new List<attr>();
        }

        [System.Xml.Serialization.XmlElementAttribute("a")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<attr> a
        {
            get
            {
                return this._a;
            }
            set
            {
                if (((this._a == null)
                            || (_a.Equals(value) != true)))
                {
                    this._a = value;
                    this.OnPropertyChanged("a");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "attr", Namespace = "urn:zimbraAdminExt")]
    public partial class attr : System.ComponentModel.INotifyPropertyChanged
    {

        private string _name;

        private string _value;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                if (((this._name == null)
                            || (_name.Equals(value) != true)))
                {
                    this._name = value;
                    this.OnPropertyChanged("name");
                }
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._value;
            }
            set
            {
                if (((this._value == null)
                            || (_value.Equals(value) != true)))
                {
                    this._value = value;
                    this.OnPropertyChanged("Value");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bulkIMAPImportTaskInfo", Namespace = "urn:zimbraAdminExt")]
    public partial class bulkIMAPImportTaskInfo : attrsImpl
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("GenerateBulkProvisionFileFromLDAPRequest", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "generateBulkProvisionFileFromLDAPRequest", Namespace = "urn:zimbraAdminExt")]
    public partial class generateBulkProvisionFileFromLDAPRequest : attrsImpl
    {

        private string _password;

        private string _generatePassword;

        private System.Nullable<int> _genPasswordLength;

        private string _fileFormat;

        private string _mustChangePassword;

        private System.Nullable<int> _maxResults;

        private string _sMTPHost;

        private string _sMTPPort;

        private string _importMails;

        private string _importContacts;

        private string _importCalendar;

        private string _importTasks;

        private string _importJunk;

        private string _importDeletedItems;

        private string _ignorePreviouslyImported;

        private string _invalidSSLOk;

        private string _mapiProfile;

        private string _mapiServer;

        private string _mapiLogonUserDN;

        private string _zimbraAdminLogin;

        private string _zimbraAdminPassword;

        private string _targetDomainName;

        private string _provisionUsers;

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this._password;
            }
            set
            {
                if (((this._password == null)
                            || (_password.Equals(value) != true)))
                {
                    this._password = value;
                    this.OnPropertyChanged("password");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string generatePassword
        {
            get
            {
                return this._generatePassword;
            }
            set
            {
                if (((this._generatePassword == null)
                            || (_generatePassword.Equals(value) != true)))
                {
                    this._generatePassword = value;
                    this.OnPropertyChanged("generatePassword");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int genPasswordLength
        {
            get
            {
                if (this._genPasswordLength.HasValue)
                {
                    return this._genPasswordLength.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_genPasswordLength.Equals(value) != true))
                {
                    this._genPasswordLength = value;
                    this.OnPropertyChanged("genPasswordLength");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool genPasswordLengthSpecified
        {
            get
            {
                return this._genPasswordLength.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._genPasswordLength = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileFormat
        {
            get
            {
                return this._fileFormat;
            }
            set
            {
                if (((this._fileFormat == null)
                            || (_fileFormat.Equals(value) != true)))
                {
                    this._fileFormat = value;
                    this.OnPropertyChanged("fileFormat");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mustChangePassword
        {
            get
            {
                return this._mustChangePassword;
            }
            set
            {
                if (((this._mustChangePassword == null)
                            || (_mustChangePassword.Equals(value) != true)))
                {
                    this._mustChangePassword = value;
                    this.OnPropertyChanged("mustChangePassword");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int maxResults
        {
            get
            {
                if (this._maxResults.HasValue)
                {
                    return this._maxResults.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_maxResults.Equals(value) != true))
                {
                    this._maxResults = value;
                    this.OnPropertyChanged("maxResults");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool maxResultsSpecified
        {
            get
            {
                return this._maxResults.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._maxResults = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPHost
        {
            get
            {
                return this._sMTPHost;
            }
            set
            {
                if (((this._sMTPHost == null)
                            || (_sMTPHost.Equals(value) != true)))
                {
                    this._sMTPHost = value;
                    this.OnPropertyChanged("SMTPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPPort
        {
            get
            {
                return this._sMTPPort;
            }
            set
            {
                if (((this._sMTPPort == null)
                            || (_sMTPPort.Equals(value) != true)))
                {
                    this._sMTPPort = value;
                    this.OnPropertyChanged("SMTPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importMails
        {
            get
            {
                return this._importMails;
            }
            set
            {
                if (((this._importMails == null)
                            || (_importMails.Equals(value) != true)))
                {
                    this._importMails = value;
                    this.OnPropertyChanged("importMails");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importContacts
        {
            get
            {
                return this._importContacts;
            }
            set
            {
                if (((this._importContacts == null)
                            || (_importContacts.Equals(value) != true)))
                {
                    this._importContacts = value;
                    this.OnPropertyChanged("importContacts");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importCalendar
        {
            get
            {
                return this._importCalendar;
            }
            set
            {
                if (((this._importCalendar == null)
                            || (_importCalendar.Equals(value) != true)))
                {
                    this._importCalendar = value;
                    this.OnPropertyChanged("importCalendar");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importTasks
        {
            get
            {
                return this._importTasks;
            }
            set
            {
                if (((this._importTasks == null)
                            || (_importTasks.Equals(value) != true)))
                {
                    this._importTasks = value;
                    this.OnPropertyChanged("importTasks");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importJunk
        {
            get
            {
                return this._importJunk;
            }
            set
            {
                if (((this._importJunk == null)
                            || (_importJunk.Equals(value) != true)))
                {
                    this._importJunk = value;
                    this.OnPropertyChanged("importJunk");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string importDeletedItems
        {
            get
            {
                return this._importDeletedItems;
            }
            set
            {
                if (((this._importDeletedItems == null)
                            || (_importDeletedItems.Equals(value) != true)))
                {
                    this._importDeletedItems = value;
                    this.OnPropertyChanged("importDeletedItems");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ignorePreviouslyImported
        {
            get
            {
                return this._ignorePreviouslyImported;
            }
            set
            {
                if (((this._ignorePreviouslyImported == null)
                            || (_ignorePreviouslyImported.Equals(value) != true)))
                {
                    this._ignorePreviouslyImported = value;
                    this.OnPropertyChanged("ignorePreviouslyImported");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvalidSSLOk
        {
            get
            {
                return this._invalidSSLOk;
            }
            set
            {
                if (((this._invalidSSLOk == null)
                            || (_invalidSSLOk.Equals(value) != true)))
                {
                    this._invalidSSLOk = value;
                    this.OnPropertyChanged("InvalidSSLOk");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapiProfile
        {
            get
            {
                return this._mapiProfile;
            }
            set
            {
                if (((this._mapiProfile == null)
                            || (_mapiProfile.Equals(value) != true)))
                {
                    this._mapiProfile = value;
                    this.OnPropertyChanged("MapiProfile");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapiServer
        {
            get
            {
                return this._mapiServer;
            }
            set
            {
                if (((this._mapiServer == null)
                            || (_mapiServer.Equals(value) != true)))
                {
                    this._mapiServer = value;
                    this.OnPropertyChanged("MapiServer");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MapiLogonUserDN
        {
            get
            {
                return this._mapiLogonUserDN;
            }
            set
            {
                if (((this._mapiLogonUserDN == null)
                            || (_mapiLogonUserDN.Equals(value) != true)))
                {
                    this._mapiLogonUserDN = value;
                    this.OnPropertyChanged("MapiLogonUserDN");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZimbraAdminLogin
        {
            get
            {
                return this._zimbraAdminLogin;
            }
            set
            {
                if (((this._zimbraAdminLogin == null)
                            || (_zimbraAdminLogin.Equals(value) != true)))
                {
                    this._zimbraAdminLogin = value;
                    this.OnPropertyChanged("ZimbraAdminLogin");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZimbraAdminPassword
        {
            get
            {
                return this._zimbraAdminPassword;
            }
            set
            {
                if (((this._zimbraAdminPassword == null)
                            || (_zimbraAdminPassword.Equals(value) != true)))
                {
                    this._zimbraAdminPassword = value;
                    this.OnPropertyChanged("ZimbraAdminPassword");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetDomainName
        {
            get
            {
                return this._targetDomainName;
            }
            set
            {
                if (((this._targetDomainName == null)
                            || (_targetDomainName.Equals(value) != true)))
                {
                    this._targetDomainName = value;
                    this.OnPropertyChanged("TargetDomainName");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provisionUsers
        {
            get
            {
                return this._provisionUsers;
            }
            set
            {
                if (((this._provisionUsers == null)
                            || (_provisionUsers.Equals(value) != true)))
                {
                    this._provisionUsers = value;
                    this.OnPropertyChanged("provisionUsers");
                }
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("BulkImportAccountsResponse", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "bulkImportAccountsResponse", Namespace = "urn:zimbraAdminExt")]
    public partial class bulkImportAccountsResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private System.Nullable<int> _totalCount;

        private System.Nullable<int> _skippedAccountCount;

        private string _sMTPHost;

        private string _sMTPPort;

        private System.Nullable<int> _status;

        private System.Nullable<int> _provisionedCount;

        private System.Nullable<int> _skippedCount;

        private System.Nullable<int> _errorCount;

        private string _fileToken;

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalCount
        {
            get
            {
                if (this._totalCount.HasValue)
                {
                    return this._totalCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_totalCount.Equals(value) != true))
                {
                    this._totalCount = value;
                    this.OnPropertyChanged("totalCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool totalCountSpecified
        {
            get
            {
                return this._totalCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._totalCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int skippedAccountCount
        {
            get
            {
                if (this._skippedAccountCount.HasValue)
                {
                    return this._skippedAccountCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_skippedAccountCount.Equals(value) != true))
                {
                    this._skippedAccountCount = value;
                    this.OnPropertyChanged("skippedAccountCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool skippedAccountCountSpecified
        {
            get
            {
                return this._skippedAccountCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._skippedAccountCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPHost
        {
            get
            {
                return this._sMTPHost;
            }
            set
            {
                if (((this._sMTPHost == null)
                            || (_sMTPHost.Equals(value) != true)))
                {
                    this._sMTPHost = value;
                    this.OnPropertyChanged("SMTPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPPort
        {
            get
            {
                return this._sMTPPort;
            }
            set
            {
                if (((this._sMTPPort == null)
                            || (_sMTPPort.Equals(value) != true)))
                {
                    this._sMTPPort = value;
                    this.OnPropertyChanged("SMTPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                if (this._status.HasValue)
                {
                    return this._status.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_status.Equals(value) != true))
                {
                    this._status = value;
                    this.OnPropertyChanged("status");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this._status.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._status = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int provisionedCount
        {
            get
            {
                if (this._provisionedCount.HasValue)
                {
                    return this._provisionedCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_provisionedCount.Equals(value) != true))
                {
                    this._provisionedCount = value;
                    this.OnPropertyChanged("provisionedCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool provisionedCountSpecified
        {
            get
            {
                return this._provisionedCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._provisionedCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int skippedCount
        {
            get
            {
                if (this._skippedCount.HasValue)
                {
                    return this._skippedCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_skippedCount.Equals(value) != true))
                {
                    this._skippedCount = value;
                    this.OnPropertyChanged("skippedCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool skippedCountSpecified
        {
            get
            {
                return this._skippedCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._skippedCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int errorCount
        {
            get
            {
                if (this._errorCount.HasValue)
                {
                    return this._errorCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_errorCount.Equals(value) != true))
                {
                    this._errorCount = value;
                    this.OnPropertyChanged("errorCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool errorCountSpecified
        {
            get
            {
                return this._errorCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._errorCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileToken
        {
            get
            {
                return this._fileToken;
            }
            set
            {
                if (((this._fileToken == null)
                            || (_fileToken.Equals(value) != true)))
                {
                    this._fileToken = value;
                    this.OnPropertyChanged("fileToken");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("GenerateBulkProvisionFileFromLDAPResponse", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "generateBulkProvisionFileFromLDAPResponse", Namespace = "urn:zimbraAdminExt")]
    public partial class generateBulkProvisionFileFromLDAPResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private System.Nullable<int> _totalCount;

        private System.Nullable<int> _domainCount;

        private System.Nullable<int> _skippedAccountCount;

        private System.Nullable<int> _skippedDomainCount;

        private string _sMTPHost;

        private string _sMTPPort;

        private string _fileToken;

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int totalCount
        {
            get
            {
                if (this._totalCount.HasValue)
                {
                    return this._totalCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_totalCount.Equals(value) != true))
                {
                    this._totalCount = value;
                    this.OnPropertyChanged("totalCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool totalCountSpecified
        {
            get
            {
                return this._totalCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._totalCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int domainCount
        {
            get
            {
                if (this._domainCount.HasValue)
                {
                    return this._domainCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_domainCount.Equals(value) != true))
                {
                    this._domainCount = value;
                    this.OnPropertyChanged("domainCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool domainCountSpecified
        {
            get
            {
                return this._domainCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._domainCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int skippedAccountCount
        {
            get
            {
                if (this._skippedAccountCount.HasValue)
                {
                    return this._skippedAccountCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_skippedAccountCount.Equals(value) != true))
                {
                    this._skippedAccountCount = value;
                    this.OnPropertyChanged("skippedAccountCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool skippedAccountCountSpecified
        {
            get
            {
                return this._skippedAccountCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._skippedAccountCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int skippedDomainCount
        {
            get
            {
                if (this._skippedDomainCount.HasValue)
                {
                    return this._skippedDomainCount.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                if ((_skippedDomainCount.Equals(value) != true))
                {
                    this._skippedDomainCount = value;
                    this.OnPropertyChanged("skippedDomainCount");
                }
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool skippedDomainCountSpecified
        {
            get
            {
                return this._skippedDomainCount.HasValue;
            }
            set
            {
                if (value == false)
                {
                    this._skippedDomainCount = null;
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPHost
        {
            get
            {
                return this._sMTPHost;
            }
            set
            {
                if (((this._sMTPHost == null)
                            || (_sMTPHost.Equals(value) != true)))
                {
                    this._sMTPHost = value;
                    this.OnPropertyChanged("SMTPHost");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SMTPPort
        {
            get
            {
                return this._sMTPPort;
            }
            set
            {
                if (((this._sMTPPort == null)
                            || (_sMTPPort.Equals(value) != true)))
                {
                    this._sMTPPort = value;
                    this.OnPropertyChanged("SMTPPort");
                }
            }
        }

        [System.Xml.Serialization.XmlElementAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileToken
        {
            get
            {
                return this._fileToken;
            }
            set
            {
                if (((this._fileToken == null)
                            || (_fileToken.Equals(value) != true)))
                {
                    this._fileToken = value;
                    this.OnPropertyChanged("fileToken");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("GetBulkIMAPImportTaskListRequest", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "getBulkIMAPImportTaskListRequest", Namespace = "urn:zimbraAdminExt")]
    public partial class getBulkIMAPImportTaskListRequest : System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("GetBulkIMAPImportTaskListResponse", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "getBulkIMAPImportTaskListResponse", Namespace = "urn:zimbraAdminExt")]
    public partial class getBulkIMAPImportTaskListResponse : System.ComponentModel.INotifyPropertyChanged
    {

        private List<bulkIMAPImportTaskInfo> _task;

        public getBulkIMAPImportTaskListResponse()
        {
            this._task = new List<bulkIMAPImportTaskInfo>();
        }

        [System.Xml.Serialization.XmlElementAttribute("task")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<bulkIMAPImportTaskInfo> task
        {
            get
            {
                return this._task;
            }
            set
            {
                if (((this._task == null)
                            || (_task.Equals(value) != true)))
                {
                    this._task = value;
                    this.OnPropertyChanged("task");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("PurgeBulkIMAPImportTasksRequest", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "purgeBulkIMAPImportTasksRequest", Namespace = "urn:zimbraAdminExt")]
    public partial class purgeBulkIMAPImportTasksRequest : System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:zimbraAdminExt")]
    [System.Xml.Serialization.XmlRootAttribute("PurgeBulkIMAPImportTasksResponse", Namespace = "urn:zimbraAdminExt", IsNullable = false)]
    [System.Runtime.Serialization.DataContractAttribute(Name = "purgeBulkIMAPImportTasksResponse", Namespace = "urn:zimbraAdminExt")]
    public partial class purgeBulkIMAPImportTasksResponse : System.ComponentModel.INotifyPropertyChanged
    {

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        public virtual void OnPropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler handler = this.PropertyChanged;
            if ((handler != null))
            {
                handler(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore
