//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubCloud.Administratie.WebControls
{
    public partial class ClubCloud_Baanschema_InsertUserControl 
    {
        /// <summary>
        /// ClubCloud_Baanschema_DataSource control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    	protected global::ClubCloud.Common.Controls.ClubCloudDataSource ClubCloud_Baanschema_DataSource;
    
    	/// <summary>
        /// udp_ClubCloud_Baanschema control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        //protected global::System.Web.UI.UpdatePanel udp_Baanschema;
    
        /// <summary>
        /// Baanschema_Validator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator Baanschema_Validator;
    
    	/// <summary>
        /// Baanschema_Summary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ValidationSummary Baanschema_Summary;
    
        /// <summary>
        /// InsertBaanschemaform control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView InsertBaanschemaform;
    
    }
}

